### PR TITLE
Completed the Android Arduino bridge testing 

### LINKED ISSUE #253: Android interface for UART testing
**Actual Behaviour.**  
There is no bridge between Arduino source code and Android app.

**Expected Behaviour**  
1. Need #250 and #251 fixed for this for someone to complete.
2. Once they are complete, test and complete the bridge between UI created in #250 with the source code created in #251 

**Steps to reproduce it**  
> Not applicable

**Additional context**  
> None

**Would you like to work on the issue?**
Issue for GSoC

### PR DESCRIPTION
**Pull request by suresh-gandhi**
Fixes #253.

**Changes**: 
* Completed the validated the Android-Arduino bridge testing and did the necessary changes in TestModeActivity by removing some bugs present for the same.
* Made some UI changes as well.
* Validated the changes through TX/RX led blinks in the hardware as well as through display area's received text.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3241611/app-debug.zip)

### CODE REVIEW

**Comment by suresh-gandhi** [comment]
@CloudyPadmal Arduino Android bridge is checked and tested. It is working. However, further scope of improvement still lies for the same Activity (in terms of UI enhancement and other edge cases handling) which I left intentionally with this being just a TestActivity for validating the serial connection established between Arduino & Android. If required we can make improvements as we go along. Please let me know your thoughts and correct me if I am wrong.

File: app/src/main/java/io/neurolab/main/TestModeActivity.java [hunk 1]
```diff
@@ -71,15 +75,15 @@ public void onReceive(Context context, Intent intent) {
                         serialPort = UsbSerialDevice.createUsbSerialDevice(device, connection);
                         if (serialPort != null) {
                             if (serialPort.open()) { //Set Serial Connection Parameters.
-                                writeBtn.setEnabled(true);
-                                serialPort.setBaudRate(baudRate);
+                                setUiEnabled(true); //Enable Buttons in UI
+                                serialPort.setBaudRate(9600);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/neurolab/main/TestModeActivity.java]: This value need to be set from the spinner

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
No we don't need to have a super UI here. This is for testing the backend. Next step is to make a singleton so that we can access the connection from anywhere in the app. Before that, we need to add SD card read function #271

**Comment by CloudyPadmal** [comment]
I'll test this with a board myself and confirm. Anyways thanks for the PR. Also note codacy issues

**Comment by suresh-gandhi** [comment]
@CloudyPadmal did the changes. Codacy just tells to make one Button reference a local variable which I didn't do for consistency with other references and possible future changes. Please have a look.

File: app/src/main/java/io/neurolab/main/TestModeActivity.java [hunk 2]
```diff
@@ -91,77 +95,114 @@ public void onReceive(Context context, Intent intent) {
...
-     * @param view
+    /*
+        Searches for all connected devices and then check if the vendor ID of the Arduino
+        matches that of a connected device.
+        If found, permission must be requested from the user.
      */
-    public void beginRead(View view) {
-        deviceConnector.checkConnection(this);
-        device = deviceConnector.getDevice();
+    private void searchForArduinoDevice(){
```
Comment (jddeep) [inline app/src/main/java/io/neurolab/main/TestModeActivity.java:146]: @suresh-gandhi A similar function exists in DeviceConnector class for the same purpose. If you want this function here, then you can remove it from the other place or use it from there. Minimizes redundancy.

Comment (suresh-gandhi) [reply app/src/main/java/io/neurolab/main/TestModeActivity.java:146]: @jddeep we will actually convert it into a utility class and then implement the singleton pattern to make it accessible everywhere in the app. I don't think we should do that for two classes and therefore I kept the code in a single class. Maybe for some helper functions, it may work but this is not a helper function.

Comment (jddeep) [reply app/src/main/java/io/neurolab/main/TestModeActivity.java:146]: Yes. Please remove the same function from the DeviceConnector as this ain't a helper method.

**Review by CloudyPadmal — APPROVED** [review]
