### PR TITLE
fix: improved rocket animation and fixed initial startup

### LINKED ISSUE #406: Configure Focus animation according to data and update speed
**Describe the bug**
Currently, the rocket animation uses a linear interpolator. We can have a acceleration one for going up, and slow it down while coming back.

**Expected Behavior**
Configure Focus animation according to data and update speed

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Would you like to work on the issue?**
@adityastic @jddeep

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #406 

Changes:
- Updated custom view
- fixed fragment startup

Screenshot:
https://drive.google.com/open?id=1-Covc-aG_Yzu4slKl-ZTrSsIms3OjmrC

### CODE REVIEW

File: app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java [hunk 1]
```diff
@@ -70,14 +69,83 @@ public void animateRocket(double[] data, Activity activity) {
 
         double value = Double.parseDouble(Double.toString(data[count]).substring(0, 3));
         valueAnimator[0] = ValueAnimator.ofFloat(0f, (float) -value);
-        valueAnimator[0].setInterpolator(new LinearInterpolator());
-        valueAnimator[0].setRepeatMode(ValueAnimator.REVERSE);
-        valueAnimator[0].setRepeatCount(3);
-        valueAnimator[0].setDuration(1000);
+        valueAnimator[0].setInterpolator(new AccelerateInterpolator());
+        valueAnimator[0].setDuration(500);
```
Comment (jddeep) [inline app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java]: If this is responsible for the up animation, then we can make it `600`. Looks less abrupt.

**Review by jddeep — CHANGES_REQUESTED** [review]

**Review by jddeep — APPROVED** [review]

**Review by CloudyPadmal — APPROVED** [review]
