### PR TITLE
Fixes #634 Play/Pause in Meditation player.

### LINKED ISSUE #634: Play/Pause buttons in Meditation player
**Actual Behaviour.**  
Currently, there are two separate buttons in the player - one for play and other for pause which hampers UX as the user might get confused.  

**Expected Behaviour**  
In my opinion there should be only one button which is 'play' in starting and then on tap of 'play', the button should change to 'pause'.[According to the state]

**Steps to reproduce it**  
Open the Meditation player view and you'll notice the two separate buttons. 

**Additional context**  
Current - 

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by Sarthak2601**
Fixes #634 

**Changes**: 
- The pause button was made invisible initially 
- Then the onClick functions of both play and pause buttons were extended to control the buttons' visibility. 

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[mediabuttons.zip](https://github.com/fossasia/neurolab-android/files/4226862/mediabuttons.zip)

### CODE REVIEW

**Comment by Sarthak2601** [comment]
Hi ! @jddeep / @adityastic 
Please review. ;)

File: app/src/main/java/io/neurolab/activities/MeditationActivity.java [hunk 1]
```diff
@@ -75,13 +76,28 @@ private void grabNecessaryReferencesAndSetListeners() {
...
+                    playerAdapter.play();
+                    pauseButton.setVisibility(View.VISIBLE);
+                    playButton.setVisibility(View.GONE);
+                });
         resetButton.setOnClickListener(
-                view -> playerAdapter.reset());
+                view -> {
+                    playerAdapter.reset();
+                    playButton.setVisibility(View.VISIBLE);
+                    pauseButton.setVisibility(View.INVISIBLE);
```
Comment (jddeep) [inline app/src/main/java/io/neurolab/activities/MeditationActivity.java]: @Sarthak2601 Why not `GONE`?

Comment (Sarthak2601) [reply app/src/main/java/io/neurolab/activities/MeditationActivity.java]: Yes, we can do that as well. It seems that any of these will work so might as well use `INVISIBLE` only.

**Review by adityastic — APPROVED** [review]
RTM @jddeep

File: app/src/main/java/io/neurolab/activities/MeditationActivity.java (hunk 1 above)
Comment (jddeep) [reply app/src/main/java/io/neurolab/activities/MeditationActivity.java]: @Sarthak2601 Please follow one pattern. VISIBLE/GONE OR VISIBLE/INVISIBLE. Also remember, in case of invisible, the view is actually there and takes that place whereas in case of gone it completely disappears from the layout

Comment (Sarthak2601) [reply app/src/main/java/io/neurolab/activities/MeditationActivity.java]: Done

**Review by jddeep — APPROVED** [review]
