### PR TITLE
Removed the unwanted FAB as required.

### LINKED ISSUE #29: The Snackbar FAB is not needed.
**Actual Behaviour** The unnecessary FAB.

Please state here what is currently happening.

**Expected Behaviour** Clean background.

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
Yes, I am working on that issue.

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #29 and #17 and #32 

**Changes**: Removed the FAB.

**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration]

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

### CODE REVIEW

**Comment by jddeep** [comment]
@CloudyPadmal @mariobehling kindly review and merge the PR. Thanks.

**Comment by CloudyPadmal** [comment]
Hi @jddeep !
This PR contains changes related to #28 . Reason is that your current working branches are not tracking the upstream branch it seems. Please update the PR. Thanks!

**Comment by jddeep** [comment]
@CloudyPadmal Yeah I merged this branch to my origin development branch. So the changes in this PR are also present in #28 . So you can directly review that. And if you say I will close it. Thanks.

**Comment by CloudyPadmal** [comment]
@jddeep a single PR should be fixing a single issue. I think it's good that you revise [FOSSASIA best practices](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) again.

**Comment by jddeep** [comment]
@CloudyPadmal so can you tell me about the reason for this PR not getting Travis builds. Should I fetch upstream after checking out from this branch ?

**Comment by jddeep** [comment]
> @jddeep a single PR should be fixing a single issue. I think it's good that you revise [FOSSASIA best practices](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) again.

Yeah, I follow them sir, that is why I opened a separate issue and a PR for the same but was forced to merge it in my origin development branch due to the failed Travis builds. I guess I have to fetch the upstream again from this branch. What do you suggest @CloudyPadmal ?

File: app/src/main/java/io/neurolab/MainActivity.java [hunk 1]
```diff
@@ -14,19 +14,28 @@
...
+
     @Override
     protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         setContentView(R.layout.activity_main);
         Toolbar toolbar = findViewById(R.id.toolbar);
         setSupportActionBar(toolbar);
 
+        rocketimage = findViewById(R.id.rocketimage);
         FloatingActionButton fab = findViewById(R.id.fab);
```
Comment (CloudyPadmal) [inline app/src/main/java/io/neurolab/MainActivity.java]: Travis build is failing because of this. Have you at-least run this code and installed on mobile phone before making the PR?

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]

**Comment by CloudyPadmal** [comment]
@jddeep I suggest you follow https://github.com/fossasia/pslab-android#how-to-git-squash again and update the branch to have only the changes addressed in the relevant issue.

File: app/src/main/java/io/neurolab/MainActivity.java (hunk 1 above)
Comment (jddeep) [reply app/src/main/java/io/neurolab/MainActivity.java]: @CloudyPadmal yes sir. Take a look at the gif in #28 . It is the working prototype on my device only.

Comment (CloudyPadmal) [reply app/src/main/java/io/neurolab/MainActivity.java]: How can it be working? You have removed the id for `fab` and the build not failing once run? #28 is not #30 and in #28 it is not removed.

Comment (jddeep) [reply app/src/main/java/io/neurolab/MainActivity.java]: Yes in #30 the fab is removed but after merging the change in this branch into development #28 should have the change too. And @CloudyPadmal sir why would the build fail? the fab has been removed but the rocket image animation is still all there intact with the res untouched.

Comment (CloudyPadmal) [reply app/src/main/java/io/neurolab/MainActivity.java]: This is too much conversation. Why can't you fix it? The build is failing and why are you justifying it? Why do you need to merge every PR into other PRs?

This is basic Android development. If a resource referred in a source file has been removed the build fails. Please do some research and fix it. Thanks.

Comment (CloudyPadmal) [reply app/src/main/java/io/neurolab/MainActivity.java]: This issue is not resolved

Comment (jddeep) [reply app/src/main/java/io/neurolab/MainActivity.java]: @CloudyPadmal give me some time I am looking into it. There is no build failure at my side. But since the Travis build is failing I am definitely looking into it. Thank you.

**Comment by jddeep** [comment]
> @jddeep I suggest you follow https://github.com/fossasia/pslab-android#how-to-git-squash again and update the branch to have only the changes addressed in the relevant issue.

**Comment by jddeep** [comment]
While force pushing from ` branch2 ` this PR was closed automatically. But anyways the changes intended through this PR is the same as #31 . Thanks

**Comment by jddeep** [comment]
@CloudyPadmal #30 has been reopened as required with successful Travis builds. Kindly look into and merge as required. Thank you.

**Comment by jddeep** [comment]
@CloudyPadmal @mariobehling The PR has been sitting for quite some while now. Kindly look into it. Thank you.

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
This PR still contains changes proposed in #28

**Comment by jddeep** [comment]
@CloudyPadmal now this PR contains changes only related to the mentioned issue. Thank you.

**Review by CloudyPadmal — APPROVED** [review]
