### PR TITLE
Fixed Meditation Bug

### LINKED ISSUE #485: Meditate Activity Bug
**Describe the bug**
When the developer mode is selected from settings, the meditation cardview should be visible when we switch to neurolab activity. But either the app has to be closed or the orientation has to change for that to happen.
>>Below is a gif showing the behaviour:

WhatsAppVideo2019-09-30at24556PM

**Expected Behaviour**
Meditation option should be visible in the main activity immediately after enabling developer  mode in settings activity.

**Steps to reproduce it**
Activity life cycle should be managed properly.

**Would you like to work on the issue?**
YES.

### PR DESCRIPTION
**Pull request by kshitiz-kumar**
Fixes #485 

**Changes**: Made changes in the settings activity to reload neurolab activity whenever user hits the back button from settings activity.

**Screenshot/s for the changes**: 
MeditationBug

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3678095/app-debug.zip)

### CODE REVIEW

File: app/src/main/java/io/neurolab/main/NeuroLab.java [hunk 1]
```diff
@@ -75,18 +75,14 @@
...
+    private int launcherSleepTime;
     private UsbSerialInterface.UsbReadCallback readCallback = new UsbSerialInterface.UsbReadCallback() { //Defining a Callback which triggers whenever data is read.
         @Override
         public void onReceivedData(byte[] arg0) {
-            try {
-                deviceData = new String(arg0, "UTF-8");
-            } catch (UnsupportedEncodingException e) {
-                e.printStackTrace();
-            }
+            deviceData = new String(arg0, StandardCharsets.UTF_8);
```
Comment (jddeep) [inline app/src/main/java/io/neurolab/main/NeuroLab.java]: Why this change? Please do not change any of the hardware-related code now.

**Review by jddeep — CHANGES_REQUESTED** [review]

**Comment by jddeep** [comment]
@kshitiz-kumar Also make sure the splash screen doesn't start while going back from the settings to home activity.

File: app/src/main/java/io/neurolab/main/NeuroLab.java (hunk 1 above)
Comment (kshitiz-kumar) [reply app/src/main/java/io/neurolab/main/NeuroLab.java]: That's a pure mistake. I'll make the appropriate changes.

**Comment by kshitiz-kumar** [comment]
> @kshitiz-kumar Also make sure the splash screen doesn't start while going back from the settings to home activity.

@jddeep well I am working on splash screen, till then do not merge this PR

**Comment by kshitiz-kumar** [comment]
@jddeep please review the chnages.
Below is a gif for your reference
WhatsAppVideo2019-10-05at123441A

**Review by jddeep — APPROVED** [review]

**Comment by kshitiz-kumar** [comment]
@adityastic @CloudyPadmal  please review and merge

**Review by CloudyPadmal — APPROVED** [review]
