### PR TITLE
fix : Redundant views in Data Logger Screen.

### LINKED ISSUE #503: Duplicate Items in Data Logger screen each time activity is opened.
**Describe the bug**

**Expected Behavior**
Data logger screen should not contain redundant views when opened multiple times.

**Steps to reproduce it**
1) Go to Logged Data Screen.
2) There are 4 files there, now go back and revisit the same screen.

**LogCat for the issue**
NA

**Screenshots of the issue**
ezgif com-optimize

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by dipu989**
Fixes #503 

**Changes**:
Fixed redundant views in data logger screen.

**Screenshot/s for the changes**:
ezgif com-optimize

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:
[apkDebug.zip](https://github.com/fossasia/neurolab-android/files/3730799/apkDebug.zip)

### CODE REVIEW

File: app/src/main/java/io/neurolab/activities/DataLoggerActivity.java [hunk 1]
```diff
@@ -55,6 +55,8 @@ protected void onCreate(Bundle savedInstanceState) {
     }
 
     private void showLoggedDataList(File appDir) {
+        filesList.clear();
+        fileList.clear();
```
Comment (jddeep) [inline app/src/main/java/io/neurolab/activities/DataLoggerActivity.java]: make a seperate method for these something like `clearRedundantFiles()`

**Review by jddeep — CHANGES_REQUESTED** [review]

File: app/src/main/java/io/neurolab/activities/DataLoggerActivity.java (hunk 1 above)
Comment (dipu989) [reply app/src/main/java/io/neurolab/activities/DataLoggerActivity.java]: Done with changes! Please check.

**Review by jddeep — APPROVED** [review]

**Review by CloudyPadmal — APPROVED** [review]
