### PR TITLE
fix : Display message when no files on device.

### LINKED ISSUE #533: Show meaningful message when no dataset present in the device
**Actual Behaviour.**  
Nothing appears on the share data activity when the device has no datasets present.

**Expected Behaviour**  
There should be a message in Share data activity when there are no datasets
in the device.

**Steps to reproduce it**  
If there are no datasets present, click on the share button from the navigation drawer.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by dipu989**
Fixes #533 

**Changes**:
Show message in Share Data activity in case there are no datasets on the device.

**Screenshot/s for the changes**: 

**Screenshot**
20191128_122525-min

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing (Latest)**: 
[apkDebug.zip](https://github.com/fossasia/neurolab-android/files/3900322/apkDebug.zip)

### CODE REVIEW

File: app/src/main/java/io/neurolab/activities/ShareDataActivity.java [hunk 1]
```diff
@@ -70,6 +75,15 @@ protected void onCreate(Bundle savedInstanceState) {
                 newFileName[i] = files[i].getName();
                 j++;
             }
+            numberOfFiles.setVisibility(View.INVISIBLE);
+            Toast.makeText(this, R.string.share_screen_toast, Toast.LENGTH_SHORT).show();
+        }
+
+        if(appDir.listFiles().length == 0)
+        {
```
Comment (CloudyPadmal) [inline app/src/main/java/io/neurolab/activities/ShareDataActivity.java]: We use inline brackets

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]
As I can see from the sample, when a user deletes, have to come back to see the no files message. Can you implement it in such a way that, once the last dataset is deleted, the message is shown?

File: app/src/main/java/io/neurolab/activities/ShareDataActivity.java (hunk 1 above)
Comment (dipu989) [reply app/src/main/java/io/neurolab/activities/ShareDataActivity.java]: > As I can see from the sample, when a user deletes, have to come back to see the no files message. Can you implement it in such a way that, once the last dataset is deleted, the message is shown?

 @CloudyPadmal  The "No data to show" message and DataSet deletion is happening on different activities.
"No data to show" is being displayed in Share data activity whereas dataset Deletion is being done in Data Logger Screen.
Should I add similar code for Data Logger screen as well in this PR only?

**Review by jddeep — CHANGES_REQUESTED** [review]
@dipu989 Once the last file gets deleted, show the message in that Activity.

**Comment by jddeep** [comment]
@dipu989 Any updates? Please update the PR.

**Comment by dipu989** [comment]
> @dipu989 Any updates? Please update the PR.

@jddeep I am working on it. Will update it as soon as possible!

**Comment by jddeep** [comment]
@dipu989 Please update the GIF in the PR body and the apk. Thanks.

**Comment by dipu989** [comment]
@jddeep Updated! Please check.

**Comment by jddeep** [comment]
@dipu989 Why does on clicking the back button after deleting all files, it shows the splash screen? Please fix that.

**Comment by dipu989** [comment]
@jddeep It is not the case! Actually the GIF is getting repeated from the start so it looks like splash triggers.

**Review by jddeep — APPROVED** [review]
Also, please try to reformat your code every time. I have seen some extra spaces/lines in the code. Please take care from next time. Thanks.
