### PR TITLE
Parse channel data from recorded data to process

### LINKED ISSUE #387: Parse/extract channel Data from recorded file to be processed
**Actual Behaviour.**  
Missing Parse/extract channel Data from recorded file to be processed.

**Expected Behaviour**  
Parse/extract channel Data from recorded file to be processed

**Steps to reproduce it**  
> Not available

**Additional context**  
> Not available

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #387 

**Changes**: Parse channel data from recorded data to process.

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
https://drive.google.com/open?id=1UtOvn1PiFrYS9NvPZDRGyF0QtBWj_Iss

### CODE REVIEW

**Review by CloudyPadmal — COMMENTED** [review]
Why all your PRs are not tracking upstream? It's really confusing to review them. This PR contains all the changes from #385

**Comment by jddeep** [comment]
Yes, you are right. Actually majorly in my PRs to make new changes, I need stuff from other unmerged PRs to work. But this PR could have been an exception. Thanks will try to take care from next time.

File: app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java [hunk 1]
```diff
@@ -43,15 +43,14 @@
...
-import static io.neurolab.fragments.StatisticsFragment.convertToDouble;
 import static io.neurolab.utilities.FilePathUtil.LOG_FILE_KEY;
 
 public class FocusVisualFragment extends android.support.v4.app.Fragment {
 
     private static final int PERMISSION_REQUEST_WRITE_EXTERNAL_STORAGE_RESULT = 1;
     private boolean permission = false;
     private boolean isPlaying = false;
-    private String[] parsedData;
+    private static String[] parsedData;
```
Comment (CloudyPadmal) [inline app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java]: Local variable and this one both using the same name. Change to have a different name

**Review by CloudyPadmal — CHANGES_REQUESTED** [review]

**Review by CloudyPadmal — APPROVED** [review]
